Repository newrelic/terraform-provider-newrelic, pull requests merged in 2018-10, with the labels that each got.

#51 Update CHANGELOG.md
  CHANGELOG.md
Labels: size/XS

#46 Add support for dashboard filters
  newrelic/resource_newrelic_dashboard.go
  newrelic/resource_newrelic_dashboard_test.go
Labels: size/M

#59 Some acceptance testing cleanup
  newrelic/import_newrelic_alert_channel_test.go
  newrelic/import_newrelic_alert_condition_test.go
  newrelic/import_newrelic_alert_policy_test.go
  newrelic/import_newrelic_dashboard_test.go
  newrelic/resource_newrelic_alert_channel_test.go
  newrelic/resource_newrelic_alert_condition_test.go
  newrelic/resource_newrelic_alert_policy_channel_test.go
  newrelic/resource_newrelic_alert_policy_test.go
  newrelic/resource_newrelic_dashboard_test.go
Labels: size/L
