Repository newrelic/terraform-provider-newrelic, pull requests merged in 2019-02, with the labels that each got.

#76 include space to `format nrql_alert_condition.html.markdown` properly
  website/docs/r/nrql_alert_condition.html.markdown
Labels: documentation, size/XS

#63 Use TypeSet instead of TypeList
  newrelic/resource_newrelic_alert_condition.go
Labels: size/XS

#70 #3 Make resource_newrelic_alert_condition enabled status configurable
  newrelic/resource_newrelic_alert_condition.go
  newrelic/resource_newrelic_alert_condition_test.go
Labels: size/XS

#79 add alert condition name validation
  newrelic/resource_newrelic_alert_condition.go
  newrelic/resource_newrelic_alert_condition_test.go
  website/docs/r/alert_condition.html.markdown
Labels: documentation, size/S

#91 Add mod tidy for renovate
  renovate.json
Labels: size/XS

#92 Minor cleanup
  go.mod
  go.sum
  newrelic/resource_newrelic_alert_condition_test.go
  vendor/github.com/aws/aws-sdk-go/aws/endpoints/defaults.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/github.com/hashicorp/go-getter/checksum.go
  vendor/github.com/hashicorp/go-getter/get_http.go
  vendor/github.com/hashicorp/go-plugin/grpc_broker.go
  vendor/github.com/hashicorp/go-plugin/grpc_client.go
  vendor/github.com/hashicorp/go-plugin/grpc_controller.go
  vendor/github.com/hashicorp/go-plugin/grpc_server.go
  vendor/github.com/hashicorp/go-plugin/internal/plugin/gen.go
  vendor/github.com/hashicorp/go-plugin/internal/plugin/grpc_broker.pb.go
  vendor/github.com/hashicorp/go-plugin/internal/plugin/grpc_broker.proto
  vendor/github.com/hashicorp/go-plugin/internal/plugin/grpc_controller.pb.go
  vendor/github.com/hashicorp/go-plugin/internal/plugin/grpc_controller.proto
  vendor/github.com/hashicorp/go-plugin/testing.go
  vendor/github.com/hashicorp/hil/README.md
  vendor/github.com/hashicorp/hil/convert.go
  vendor/golang.org/x/crypto/curve25519/curve25519.go
  vendor/golang.org/x/crypto/internal/chacha20/asm_arm64.s
  vendor/golang.org/x/crypto/internal/chacha20/chacha_arm64.go
  vendor/golang.org/x/crypto/internal/chacha20/chacha_noasm.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/sys/unix/README.md
  vendor/golang.org/x/sys/unix/mkall.sh
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.pl
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_solaris_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_darwin_amd64.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#114 v1.4.0
  CHANGELOG.md
Labels: size/XS
