Repository newrelic/terraform-provider-newrelic, pull requests merged in 2019-12, with the labels that each got.

#255 test: fix failing data source test
  newrelic/data_source_newrelic_alert_channel_test.go
Labels: size/XS

#258 feat: update newrelic_synthetics_monitor_script acceptance tests
  newrelic/resource_newrelic_synthetics_monitor_script_test.go
Labels: size/S

#259 chore: use resource.ParallelTest for newrelic_synthetics_monitor_script test
  newrelic/resource_newrelic_synthetics_monitor_script_test.go
Labels: size/XS

#264 docs: update for clarity and consistency
  website/docs/d/alert_channel.html.markdown
  website/docs/d/alert_policy.html.markdown
  website/docs/d/application.html.markdown
  website/docs/d/key_transaction.html.markdown
  website/docs/d/plugin.html.markdown
  website/docs/d/plugin_component.html.markdown
  website/docs/d/synthetics_monitor.html.markdown
  website/docs/r/alert_channel.html.markdown
  website/docs/r/alert_condition.html.markdown
  website/docs/r/alert_policy.html.markdown
  website/docs/r/alert_policy_channel.html.markdown
  website/docs/r/dashboard.html.markdown
  website/docs/r/infra_alert_condition.html.markdown
  website/docs/r/insights_event.html.markdown
  website/docs/r/nrql_alert_condition.html.markdown
  website/docs/r/plugins_alert_condition.html.markdown
  website/docs/r/synthetics_alert_condition.html.markdown
  website/docs/r/synthetics_monitor.html.markdown
  website/docs/r/synthetics_monitor_script.html.markdown
Labels: documentation, size/M

#262 chore: update changelog
  CHANGELOG.md
Labels: size/XS

#263 fix: use name as filter in application lookup
  newrelic/data_source_newrelic_application.go
Labels: dependencies, size/XS

#268 docs: add missing resources and data source to sidebar
  website/docs/r/insights_event.html.markdown
  website/newrelic.erb
Labels: documentation, size/XS
