Repository newrelic/terraform-provider-newrelic, pull requests merged in 2019-11, with the labels that each got.

#133 support infrastructure alert condition runbook url
  newrelic/resource_newrelic_infra_alert_condition.go
  newrelic/resource_newrelic_infra_alert_condition_test.go
Labels: size/XS

#58 Check if alert policy exists before retrieving
  newrelic/helpers_test.go
  newrelic/resource_newrelic_alert_condition.go
  newrelic/resource_newrelic_alert_condition_test.go
  newrelic/resource_newrelic_infra_alert_condition.go
  newrelic/resource_newrelic_infra_alert_condition_test.go
  newrelic/resource_newrelic_nrql_alert_condition.go
  newrelic/resource_newrelic_nrql_alert_condition_test.go
  newrelic/resource_newrelic_synthetics_alert_condition.go
  newrelic/resource_newrelic_synthetics_alert_condition_test.go
Labels: size/M

#82 Adds validation for alerts policy names
  newrelic/resource_newrelic_alert_condition_test.go
  newrelic/resource_newrelic_alert_policy.go
  newrelic/resource_newrelic_alert_policy_test.go
  website/docs/r/alert_policy.html.markdown
Labels: documentation, size/M

#188 Linter and CI updates
  .travis.yml
  newrelic/data_source_newrelic_alert_channel.go
  newrelic/data_source_newrelic_alert_policy.go
  newrelic/data_source_newrelic_application.go
  newrelic/data_source_newrelic_key_transaction.go
  newrelic/data_source_newrelic_synthetics_monitor.go
  newrelic/resource_newrelic_synthetics_monitor.go
Labels: size/XS

#189 Add provider version to the User-Agent
  .go-version
  .travis.yml
  README.md
  go.mod
  go.sum
  newrelic/config.go
  newrelic/provider.go
  vendor/github.com/hashicorp/go-plugin/.gitignore
  vendor/github.com/hashicorp/go-plugin/grpc_client.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/LICENSE
  vendor/github.com/hashicorp/terraform-plugin-sdk/httpclient/useragent.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/meta/meta.go
  vendor/github.com/mitchellh/reflectwalk/reflectwalk.go
  vendor/github.com/spf13/afero/unionFile.go
  vendor/google.golang.org/grpc/.travis.yml
  vendor/google.golang.org/grpc/balancer.go
  vendor/google.golang.org/grpc/balancer/balancer.go
  vendor/google.golang.org/grpc/balancer/base/balancer.go
  vendor/google.golang.org/grpc/balancer_conn_wrappers.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/credentials/credentials.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/go.mod
  vendor/google.golang.org/grpc/go.sum
  vendor/google.golang.org/grpc/health/client.go
  vendor/google.golang.org/grpc/internal/envconfig/envconfig.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/transport/controlbuf.go
  vendor/google.golang.org/grpc/internal/transport/flowcontrol.go
  vendor/google.golang.org/grpc/internal/transport/handler_server.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/internal/transport/transport.go
  vendor/google.golang.org/grpc/naming/naming.go
  vendor/google.golang.org/grpc/pickfirst.go
  vendor/google.golang.org/grpc/resolver/resolver.go
  vendor/google.golang.org/grpc/resolver_conn_wrapper.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/service_config.go
  vendor/google.golang.org/grpc/serviceconfig/serviceconfig.go
  vendor/google.golang.org/grpc/status/status.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/grpc/vet.sh
  vendor/modules.txt
  version/version.go
Labels: dependencies, size/XXL

#146 newrelic_alert_condition - use TypeSet for entities list
  newrelic/resource_newrelic_alert_condition.go
Labels: size/XS

#141 Add support for outlier NRQL alert conditions
  newrelic/resource_newrelic_nrql_alert_condition.go
  newrelic/resource_newrelic_nrql_alert_condition_test.go
Labels: dependencies, size/L

#191 Linting
  .gitignore
  .golangci.yml
  GNUmakefile
  go.mod
  go.sum
  newrelic/data_source_newrelic_alert_channel_test.go
  newrelic/data_source_newrelic_alert_policy_test.go
  newrelic/data_source_newrelic_application_test.go
  newrelic/data_source_newrelic_synthetics_monitor_test.go
  newrelic/helpers.go
  newrelic/helpers_test.go
  newrelic/provider.go
  newrelic/resource_newrelic_alert_channel_test.go
  newrelic/resource_newrelic_alert_condition_test.go
  newrelic/resource_newrelic_alert_policy.go
  newrelic/resource_newrelic_alert_policy_channel_test.go
  newrelic/resource_newrelic_alert_policy_test.go
  newrelic/resource_newrelic_dashboard_test.go
  newrelic/resource_newrelic_infra_alert_condition_test.go
  newrelic/resource_newrelic_nrql_alert_condition.go
  newrelic/resource_newrelic_nrql_alert_condition_test.go
  newrelic/resource_newrelic_synthetics_alert_condition_test.go
  newrelic/resource_newrelic_synthetics_monitor_script_test.go
  newrelic/resource_newrelic_synthetics_monitor_test.go
  newrelic/validation_test.go
  scripts/gofmtcheck.sh
  version/version_test.go
Labels: size/XL

#190 chore: update CHANGELOG and README
  CHANGELOG.md
  README.md
Labels: size/M

#145 Update alert_condition.html.markdown
  website/docs/r/alert_condition.html.markdown
Labels: documentation, size/XS

#195 Update documentation
  website/docs/d/alert_channel.html.markdown
  website/docs/r/alert_condition.html.markdown
Labels: documentation, size/XS

#196 Add option to specify a ca to use in communication with newrelic apis
  go.mod
  go.sum
  newrelic/config.go
  newrelic/provider.go
  vendor/github.com/hashicorp/terraform/helper/pathorcontents/read.go
  website/docs/index.html.markdown
Labels: dependencies, documentation, size/L

#200 fix: align alert policy validation with NR's API validation
  newrelic/resource_newrelic_alert_policy.go
  newrelic/resource_newrelic_alert_policy_test.go
  website/docs/r/alert_policy.html.markdown
Labels: documentation, size/S

#202 fix: align alert condition duration constraints to NR's API constraints
  newrelic/resource_newrelic_alert_condition.go
  newrelic/resource_newrelic_alert_condition_test.go
  website/docs/r/alert_condition.html.markdown
Labels: documentation, size/M

#207 Fixes typo in docs
  website/docs/r/synthetics_monitor.html.markdown
Labels: documentation, size/XS

#206 Dashboard improvements
  go.mod
  go.sum
  newrelic/helpers_test.go
  newrelic/resource_newrelic_dashboard.go
  newrelic/resource_newrelic_dashboard_test.go
  newrelic/structure.go
  newrelic/structures_newrelic_dashboard.go
  newrelic/validation.go
  vendor/github.com/paultyng/go-newrelic/v4/api/client.go
  vendor/github.com/paultyng/go-newrelic/v4/api/types.go
  vendor/modules.txt
  version/version_test.go
  website/docs/r/dashboard.html.markdown
Labels: dependencies, documentation, size/XXL

#203 Acceptance test for manually deleted resource
  newrelic/resource_newrelic_dashboard_test.go
Labels: bug, size/S

#208 chore: update CHANGELOG - release 1.7.0
  CHANGELOG.md
Labels: size/XS

#211 update alert infra condition docs to include runbook url argument
  website/docs/r/infra_alert_condition.html.markdown
Labels: documentation, size/XS

#225 docs: add Getting Started section
  website/docs/guides/getting_started.html.markdown
  website/newrelic.erb
Labels: documentation, size/L

#228 chore: update go-newrelic dep
  go.mod
  go.sum
  vendor/github.com/paultyng/go-newrelic/v4/api/client.go
  vendor/github.com/paultyng/go-newrelic/v4/api/version.go
  vendor/modules.txt
Labels: dependencies, size/XS

#236 fix: appease linter
  GNUmakefile
  newrelic/helpers_test.go
  newrelic/structures_newrelic_dashboard.go
Labels: size/XS

#231 Document type arg
  website/docs/r/nrql_alert_condition.html.markdown
Labels: documentation, size/XS

#235 release: update CHANGELOG.md
  CHANGELOG.md
Labels: size/XS

#240 fix linting issues and enable linting in CI
  .travis.yml
  newrelic/resource_newrelic_alert_condition_test.go
  newrelic/resource_newrelic_alert_policy_test.go
  newrelic/resource_newrelic_infra_alert_condition_test.go
  newrelic/resource_newrelic_nrql_alert_condition_test.go
  newrelic/resource_newrelic_synthetics_alert_condition_test.go
Labels: size/S

#245 Additional test coverage
  newrelic/config_test.go
  newrelic/helpers_test.go
  newrelic/resource_newrelic_dashboard.go
  newrelic/structure_test.go
  newrelic/validation.go
  newrelic/validation_test.go
Labels: chore, size/L, technical-debt

#248 docs: fix formatting in dashboard docs
  website/docs/r/dashboard.html.markdown
Labels: documentation, size/XS

#247 Backfill alert condition acceptance tests
  newrelic/helpers_test.go
  newrelic/provider_test.go
  newrelic/resource_newrelic_alert_condition_test.go
  newrelic/resource_newrelic_infra_alert_condition_test.go
  newrelic/resource_newrelic_nrql_alert_condition_test.go
  newrelic/resource_newrelic_synthetics_alert_condition_test.go
Labels: size/XL, technical-debt

#249 Backfill alert policy channel acceptance tests
  newrelic/resource_newrelic_alert_policy_channel.go
  newrelic/resource_newrelic_alert_policy_channel_test.go
Labels: size/M
