Repository newrelic/terraform-provider-newrelic, pull requests merged in 2020-02, with the labels that each got.

#368 docs: Make a note about community resources and support
  website/docs/index.html.markdown
Labels: documentation, size/XS

#383 chore: prep v1.13.0 release
  CHANGELOG.md
  go.mod
  go.sum
  newrelic/provider_test.go
  vendor/github.com/newrelic/newrelic-client-go/internal/http/client.go
  vendor/github.com/newrelic/newrelic-client-go/internal/logging/logger.go
  vendor/github.com/newrelic/newrelic-client-go/internal/logging/structured_logger.go
  vendor/github.com/newrelic/newrelic-client-go/internal/version/version.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/alerts_types.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/channels.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/conditions.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/incidents.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/multi_location_synthetics_conditions.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/nrql_conditions.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/plugins_conditions.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/policies.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/policy_channels.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/synthetics_conditions.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/apm/apm_types.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/apm/applications.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/apm/deployments.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/apm/key_transactions.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/apm/labels.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/dashboards/dashboards.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/plugins/components.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/plugins/plugins.go
  vendor/modules.txt
  website/docs/index.html.markdown
Labels: dependencies, documentation, size/XL

#370 feat(infra_alert_condition): add violation_close_timer to newrelic_infra_alert_condition resource
  newrelic/resource_newrelic_infra_alert_condition.go
  newrelic/structures_newrelic_infra_alert_condition.go
  newrelic/structures_newrelic_infra_alert_condition_test.go
Labels: size/XL

#387 fix(newrelic_alert_channel): Force new resource for all config fields
  newrelic/resource_newrelic_alert_channel.go
  newrelic/resource_newrelic_alert_channel_test.go
Labels: size/S

#395 fix(alert_condition): mark condition_scope optional
  newrelic/resource_newrelic_alert_condition.go
  website/docs/r/alert_condition.html.markdown
Labels: documentation, size/XS

#397 chore: prep v1.13.1 release
  CHANGELOG.md
Labels: size/XS

#398 feat(alert_policy): add ability to add multiple channels to a policy
  newrelic/resource_newrelic_alert_policy.go
  newrelic/resource_newrelic_alert_policy_test.go
  newrelic/structures_newrelic_alert_channel.go
  newrelic/structures_newrelic_alert_channel_test.go
  website/docs/r/alert_policy.html.markdown
Labels: documentation, size/L

#408 chore: update to newrelic-client-go v0.10.0
  go.mod
  go.sum
Labels: size/XS

#407 feat(synthetics): add labels resource
  newrelic/provider.go
  newrelic/resource_newrelic_synthetics_label.go
  newrelic/resource_newrelic_synthetics_label_test.go
  vendor/github.com/newrelic/newrelic-client-go/internal/http/client.go
  vendor/github.com/newrelic/newrelic-client-go/internal/http/test_helpers.go
  vendor/github.com/newrelic/newrelic-client-go/internal/version/version.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/config/config.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/synthetics/monitor_labels.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/synthetics/monitor_scripts.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/synthetics/monitors.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/synthetics/secure_credentials.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/synthetics/synthetics.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/synthetics/synthetics_types.go
  vendor/modules.txt
  website/docs/r/synthetics_label.html.markdown
  website/newrelic.erb
Labels: dependencies, documentation, size/XL

#409 feat(synthetics): add secure credentials resource
  newrelic/data_source_newrelic_synthetics_secure_credential.go
  newrelic/data_source_newrelic_synthetics_secure_credential_test.go
  newrelic/provider.go
  newrelic/resource_newrelic_synthetics_secure_credential.go
  newrelic/resource_newrelic_synthetics_secure_credential_test.go
  newrelic/structures_newrelic_synthetics_secure_credential.go
  website/docs/d/synthetics_secure_credential.html.markdown
  website/docs/r/synthetics_secure_credential.html.markdown
  website/newrelic.erb
Labels: documentation, size/XL

#411 fix(provider): deprecate and re-enable the use of infra_api_url
  newrelic/provider.go
  website/docs/index.html.markdown
Labels: documentation, size/XS

#412 chore: prepare v1.14.0 release
  CHANGELOG.md
  go.sum
Labels: size/XS

#417 Implementation of CRUD operations for NewRelic App Labels
  newrelic/provider.go
  newrelic/resource_newrelic_application_label.go
  newrelic/resource_newrelic_application_label_test.go
  website/docs/guides/getting_started.html.markdown
  website/docs/r/application_label.html.markdown
  website/newrelic.erb
Labels: documentation, enhancement, size/XL

#421 fix(nrql_alert_condition): terms should be a TypeSet
  newrelic/resource_newrelic_nrql_alert_condition.go
  newrelic/structures_newrelic_nrql_alert_condition.go
Labels: size/XS

#422 chore(application_label): deprecate resource_newrelic_application_label
  newrelic/resource_newrelic_application_label.go
  newrelic/resource_newrelic_application_label_test.go
  website/docs/r/application_label.html.markdown
Labels: documentation, size/S

#430 Update newrelic-client-go to 0.12.0
  go.mod
  go.sum
  newrelic/config.go
  vendor/github.com/newrelic/newrelic-client-go/internal/http/auth.go
  vendor/github.com/newrelic/newrelic-client-go/internal/http/client.go
  vendor/github.com/newrelic/newrelic-client-go/internal/http/test_helpers.go
  vendor/github.com/newrelic/newrelic-client-go/internal/serialization/epoch_time.go
  vendor/github.com/newrelic/newrelic-client-go/internal/serialization/map_string_interface.go
  vendor/github.com/newrelic/newrelic-client-go/internal/version/version.go
  vendor/github.com/newrelic/newrelic-client-go/newrelic/newrelic.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/alerts_types.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/channels.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/conditions.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/incidents.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/infrastructure_conditions.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/multi_location_synthetics_conditions.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/nrql_conditions.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/plugins_conditions.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/policies.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/policy_channels.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/synthetics_conditions.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/apm/apm_types.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/apm/applications.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/apm/applications_metrics.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/apm/deployments.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/apm/key_transactions.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/apm/labels.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/config/config.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/dashboards/dashboard.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/dashboards/dashboards.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/entities/entities.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/entities/entities_types.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/entities/entity.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/entities/tags.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/nerdgraph/nerdgraph.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/synthetics/monitor_labels.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/synthetics/monitors.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/synthetics/secure_credentials.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/synthetics/synthetics_types.go
  vendor/modules.txt
Labels: dependencies, size/XXL
