Repository newrelic/terraform-provider-newrelic, pull requests merged in 2020-03, with the labels that each got.

#431 docs: list of potential metrics for newrelic_alert_condition
  website/docs/r/alert_condition.html.markdown
Labels: documentation, size/S

#365 feat(alert_policy_channels): add ability to add multiple channels to a policy
  newrelic/helpers.go
  newrelic/helpers_test.go
  newrelic/resource_newrelic_alert_policy_channel.go
  newrelic/resource_newrelic_alert_policy_channel_test.go
  newrelic/structures_newrelic_alert_policy_channel.go
  newrelic/structures_newrelic_alert_policy_channel_test.go
  website/docs/r/alert_policy_channel.html.markdown
Labels: documentation, enhancement, size/XL

#441 Prepare v1.15.0 release
  CHANGELOG.md
Labels: size/XS

#444 chore: configure Stale bot for the repo
  .github/stale.yml
Labels: size/S

#447 removed the 'servers_metric' and updated the priority item
  website/docs/r/alert_condition.html.markdown
Labels: documentation, size/XS

#450 docs(examples): add a golden signal alerting module example
  examples/README.md
  examples/modules/golden-signal-alerts/main.tf
  examples/modules/golden-signal-alerts/outputs.tf
  examples/modules/golden-signal-alerts/variables.tf
Labels: size/L

#459 chore(client): update newrelic client to v0.16.0
  go.mod
  go.sum
Labels: size/XS

#460 chore(vendor): update vendor after dependency update
  vendor/github.com/newrelic/newrelic-client-go/internal/version/version.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/entities/entity.go
  vendor/modules.txt
Labels: dependencies, size/L

#458 docs: ensure consistency
  newrelic/data_source_newrelic_alert_channel.go
  newrelic/data_source_newrelic_alert_policy.go
  newrelic/data_source_newrelic_application.go
  newrelic/data_source_newrelic_key_transaction.go
  newrelic/data_source_newrelic_plugin.go
  newrelic/data_source_newrelic_plugin_component.go
  newrelic/data_source_newrelic_synthetics_monitor.go
  newrelic/data_source_newrelic_synthetics_secure_credential.go
  newrelic/resource_newrelic_alert_channel.go
  newrelic/resource_newrelic_alert_condition.go
  newrelic/resource_newrelic_alert_policy.go
  newrelic/resource_newrelic_alert_policy_channel.go
  newrelic/resource_newrelic_application_label.go
  newrelic/resource_newrelic_dashboard.go
  newrelic/resource_newrelic_infra_alert_condition.go
  newrelic/resource_newrelic_insights_event.go
  newrelic/resource_newrelic_nrql_alert_condition.go
  newrelic/resource_newrelic_plugins_alert_condition.go
  newrelic/resource_newrelic_synthetics_alert_condition.go
  newrelic/resource_newrelic_synthetics_label.go
  newrelic/resource_newrelic_synthetics_monitor.go
  newrelic/resource_newrelic_synthetics_monitor_script.go
  newrelic/resource_newrelic_synthetics_secure_credential.go
  website/docs/d/key_transaction.html.markdown
  website/docs/d/synthetics_secure_credential.html.markdown
  website/docs/r/alert_condition.html.markdown
  website/docs/r/application_label.html.markdown
  website/docs/r/infra_alert_condition.html.markdown
  website/docs/r/nrql_alert_condition.html.markdown
  website/docs/r/plugins_alert_condition.html.markdown
  website/docs/r/synthetics_alert_condition.html.markdown
  website/docs/r/synthetics_label.html.markdown
  website/docs/r/synthetics_monitor.html.markdown
  website/docs/r/synthetics_monitor_script.html.markdown
Labels: documentation, size/XL

#465 chore: update to newrelic-client-go 0.17.0
  go.mod
  go.sum
  newrelic/structures_newrelic_alert_condition.go
  newrelic/structures_newrelic_alert_condition_test.go
  newrelic/structures_newrelic_dashboard.go
  newrelic/structures_newrelic_nrql_alert_condition.go
  newrelic/structures_newrelic_nrql_alert_condition_test.go
  newrelic/structures_newrelic_plugins_alert_condition.go
  newrelic/structures_newrelic_plugins_alert_condition_test.go
  vendor/github.com/newrelic/newrelic-client-go/internal/http/client.go
  vendor/github.com/newrelic/newrelic-client-go/internal/http/graphql.go
  vendor/github.com/newrelic/newrelic-client-go/internal/http/graphql_client.go
  vendor/github.com/newrelic/newrelic-client-go/internal/http/request.go
  vendor/github.com/newrelic/newrelic-client-go/internal/http/test_helpers.go
  vendor/github.com/newrelic/newrelic-client-go/internal/version/version.go
  vendor/github.com/newrelic/newrelic-client-go/newrelic/doc.go
  vendor/github.com/newrelic/newrelic-client-go/newrelic/newrelic.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/alerts.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/channels.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/conditions.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/doc.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/incidents.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/multi_location_synthetics_conditions.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/nrql_conditions.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/plugins_conditions.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/policies.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/policy_channels.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/synthetics_conditions.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/apm/apm.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/apm/applications.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/apm/applications_rest.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/apm/deployments.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/apm/doc.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/apm/key_transactions.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/apm/labels.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/config/config.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/config/doc.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/dashboards/dashboard.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/dashboards/dashboards.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/dashboards/dashboards_types.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/dashboards/doc.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/entities/doc.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/entities/entities.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/errors/errors.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/infrastructure/doc.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/infrastructure/infrastructure.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/nerdgraph/doc.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/nerdgraph/nerdgraph.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/plugins/doc.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/plugins/plugins.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/synthetics/doc.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/synthetics/synthetics.go
  vendor/golang.org/x/tools/go/analysis/passes/printf/printf.go
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#469 fix: import condition terms regardless of threshold format
  go.mod
  go.sum
  newrelic/resource_newrelic_alert_condition_test.go
  vendor/github.com/newrelic/newrelic-client-go/internal/version/version.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/serialization.go
  vendor/modules.txt
Labels: bug, dependencies, size/M

#470 release: v1.15.1
  CHANGELOG.md
Labels: size/XS

#473 docs: Update getting started guide
  website/docs/guides/getting_started.html.markdown
Labels: documentation, size/XS

#482 docs: use correct default synthetics_api_url in config docs
  website/docs/index.html.markdown
  website/docs/r/alert_condition.html.markdown
Labels: documentation, size/XS

#474 feat(workloads): add a workloads resource
  go.mod
  go.sum
  newrelic/config.go
  newrelic/provider.go
  newrelic/resource_newrelic_workload.go
  newrelic/resource_newrelic_workload_test.go
  newrelic/structures_newrelic_workload.go
  vendor/github.com/newrelic/newrelic-client-go/internal/version/version.go
  vendor/github.com/newrelic/newrelic-client-go/newrelic/newrelic.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/muting_rules.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/workloads/doc.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/workloads/workload.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/workloads/workloads.go
  vendor/modules.txt
  website/docs/r/workload.html.markdown
  website/newrelic.erb
Labels: dependencies, documentation, new-resource, size/XXL

#486 chore: update CHANGELOG
  CHANGELOG.md
Labels: size/XS

#488 chore(provider): add personal_api_key and account_id to provider schema and ProviderConfig
  newrelic/config.go
  newrelic/provider.go
  newrelic/provider_test.go
Labels: size/S

#489 docs(workloads): fix api key attribute name
  website/docs/index.html.markdown
  website/docs/r/workload.html.markdown
Labels: documentation, size/XS

#490 chore(newrelic): update newrelic-client-go to v0.19.0
  go.mod
  go.sum
  newrelic/resource_newrelic_workload.go
  newrelic/structures_newrelic_workload.go
  vendor/github.com/newrelic/newrelic-client-go/internal/version/version.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/nrql_conditions.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/policies.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/nerdgraph/nerdgraph.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/workloads/workload.go
  vendor/modules.txt
Labels: dependencies, size/XL

#498 Fix: violation_close_timer only applies to condition_scope instance
  newrelic/resource_newrelic_alert_condition.go
  newrelic/structures_newrelic_alert_condition.go
Labels: bug, size/S

#496 updated example usage section
  website/docs/r/infra_alert_condition.html.markdown
Labels: documentation, size/XS
