Repository newrelic/terraform-provider-newrelic, pull requests merged in 2020-06, with the labels that each got.

#626 Update newrelic-client-go
  CHANGELOG.md
  go.mod
  go.sum
  newrelic/resource_newrelic_workload_test.go
Labels: size/S

#628 chore(deps): update newrelic-client-go and testify
  go.mod
  go.sum
  newrelic/data_source_newrelic_alert_policy.go
  newrelic/resource_newrelic_alert_policy.go
  newrelic/resource_newrelic_alert_policy_test.go
  newrelic/resource_newrelic_nrql_alert_condition.go
  newrelic/resource_newrelic_nrql_alert_condition_test.go
  newrelic/structures_newrelic_alert_policy.go
Labels: size/M

#633 test(alerts): include tests for expandNrqlAlertConditionInput()
  newrelic/structures_newrelic_nrql_alert_condition.go
  newrelic/structures_newrelic_nrql_alert_condition_test.go
Labels: size/M

#636 chore(release): prep release v1.18.1
  CHANGELOG.md
Labels: size/XS

#643 fix(changelog): remove 1.18.1 from changelog, 1.19.0 is the replacement
  CHANGELOG.md
Labels: size/XS

#630 refactor(nrql_alert_condition): migrate outlier condition type to NerdGraph
  go.mod
  go.sum
  newrelic/resource_newrelic_nrql_alert_condition.go
  newrelic/resource_newrelic_nrql_alert_condition_test.go
  newrelic/structures_newrelic_nrql_alert_condition.go
  newrelic/structures_newrelic_nrql_alert_condition_test.go
  website/docs/r/nrql_alert_condition.html.markdown
Labels: documentation, size/XL

#645 chore(alerts): deprecation notice for direct use of "terms"
  examples/modules/golden-signal-alerts/main.tf
  newrelic/resource_newrelic_nrql_alert_condition.go
  newrelic/structures_newrelic_nrql_alert_condition.go
  newrelic/structures_newrelic_nrql_alert_condition_test.go
  website/docs/r/nrql_alert_condition.html.markdown
Labels: documentation, size/XL

#651 chore(alerts): remove deprecations from alert_channel resource
  newrelic/resource_newrelic_alert_channel.go
  newrelic/resource_newrelic_alert_channel_test.go
  newrelic/structures_newrelic_alert_channel.go
  website/docs/r/alert_channel.html.markdown
Labels: documentation, size/L

#652 chore(alerts): remove deprecations from alert_policy_channel resource
  newrelic/resource_newrelic_alert_policy_channel.go
  newrelic/resource_newrelic_alert_policy_channel_test.go
  newrelic/structures_newrelic_alert_policy_channel.go
  website/docs/r/alert_policy_channel.html.markdown
Labels: documentation, size/S

#654 chore(provider): remove deprecated provider param use infra_api_url
  newrelic/provider.go
  website/docs/index.html.markdown
Labels: documentation, size/XS

#653 chore(application): remove deprecated application_label resource
  newrelic/provider.go
  newrelic/resource_newrelic_application_label.go
  newrelic/resource_newrelic_application_label_test.go
  website/docs/r/application_label.html.markdown
  website/newrelic.erb
Labels: documentation, size/XL

#658 fix(alerts): handle a nil reference with more grace
  newrelic/structures_newrelic_nrql_alert_condition.go
Labels: size/XS

#664 chore: adhere to environment variable naming standard
  .github/workflows/test.yml
  README.md
  newrelic/helpers.go
  newrelic/provider.go
  newrelic/provider_test.go
  newrelic/resource_newrelic_application_settings_test.go
  newrelic/resource_newrelic_nrql_alert_condition.go
  website/docs/guides/getting_started.html.markdown
  website/docs/guides/provider_configuration.markdown
  website/docs/index.html.markdown
  website/docs/r/nrql_alert_condition.html.markdown
  website/docs/r/workload.html.markdown
Labels: documentation, size/L

#665 docs: add table for current endpoint in use per resource
  website/docs/index.html.markdown
Labels: documentation, size/XS

#667 Docs update2.x
  README.md
  website/docs/guides/getting_started.html.markdown
  website/docs/index.html.markdown
  website/docs/r/v1/alert_policy_channel.html.markdown
  website/docs/v1/index.html.markdown
  website/newrelic.erb
Labels: documentation, size/L

#677 chore: small build fixes
  .gitignore
  .go-version
Labels: size/XS

#674 Feat/entities
  examples/modules/golden-signal-alerts/main.tf
  go.sum
  newrelic/data_source_newrelic_application.go
  newrelic/data_source_newrelic_entity.go
  newrelic/data_source_newrelic_entity_test.go
  newrelic/provider.go
  website/docs/d/application.html.markdown
  website/docs/d/entity.html.markdown
  website/docs/guides/getting_started.html.markdown
  website/docs/index.html.markdown
  website/docs/r/alert_condition.html.markdown
  website/docs/r/dashboard.html.markdown
  website/newrelic.erb
Labels: documentation, new-data-source, size/XL

#679 feat(entity_tags): add an entity tag resource
  build/deps.mk
  build/lint.mk
  go.mod
  go.sum
  newrelic/data_source_newrelic_entity_test.go
  newrelic/helpers.go
  newrelic/provider.go
  newrelic/provider_test.go
  newrelic/resource_newrelic_entity_tags.go
  newrelic/resource_newrelic_entity_tags_test.go
  website/docs/d/entity.html.markdown
  website/docs/r/entity_tags.html.markdown
  website/newrelic.erb
Labels: documentation, new-resource, size/XL

#680 chore: revert GNUMakefile changes
  .github/workflows/compile.yml
  GNUmakefile
Labels: size/L

#686 chore(release): prep release v2.0.0
  CHANGELOG.md
Labels: size/S

#687 chore(tests): avoid empty NEW_RELIC_ACCOUNT_ID so make test passes
  newrelic/helpers_test.go
  newrelic/resource_newrelic_alert_condition_test.go
  newrelic/resource_newrelic_alert_policy_test.go
  newrelic/resource_newrelic_plugins_alert_condition_test.go
Labels: size/XS

#685 chore(ci): enable integration tests on push
  .github/workflows/test.yml
Labels: size/XS

#689 docs: include sidebar link for 2.x upgrade
  website/newrelic.erb
Labels: documentation, size/XS

#690 feat(eventstometrics): add an events to metrics rule resource
  build/deps.mk
  go.mod
  go.sum
  newrelic/provider.go
  newrelic/resource_newrelic_events_to_metrics_rule.go
  newrelic/resource_newrelic_events_to_metrics_rule_test.go
  tools/tools.go
  website/docs/r/events_to_metrics_rule.html.markdown
  website/newrelic.erb
Labels: documentation, new-resource, size/XL

#695 docs: include information on pinning a version
  website/docs/index.html.markdown
Labels: documentation, size/XS

#709 chore: update changelog for v2.1.0 release
  CHANGELOG.md
Labels: size/XS

#722 chore(snyk): Add security scan action
  .github/workflows/security.yml
Labels: chore, size:S

#723 docs(provider): add environment variables and schema attribute table
  website/docs/guides/provider_configuration.markdown
Labels: documentation

#729 docs(readme): update title, add link to latest documentation
  README.md
Labels: documentation
