Repository newrelic/terraform-provider-newrelic, pull requests merged in 2020-07, with the labels that each got.

#780 chore(ci): remove lint job as dependency on test-unit job
  .github/workflows/test.yml
Labels: chore

#798 fix(infra_alert_condition): [v1.x] support zero-value thresholds for infra_alert_condition resource
  .golangci.yml
  go.mod
  go.sum
  newrelic/structures_newrelic_infra_alert_condition.go
  newrelic/structures_newrelic_infra_alert_condition_test.go
Labels: v1.x

#799 chore(changelog): Update CHANGELOG for v1.20.1
  CHANGELOG.md
Labels: v1.x

#804 chore(docs): Clarify authentication used
  website/docs/index.html.markdown
Labels: documentation, size:S
