Repository newrelic/terraform-provider-newrelic, pull requests merged in 2020-04, with the labels that each got.

#497 feat(application): implement newrelic_application resource
  newrelic/data_source_newrelic_application.go
  newrelic/data_source_newrelic_application_test.go
  newrelic/provider.go
  newrelic/resource_newrelic_application.go
  newrelic/resource_newrelic_application_test.go
  newrelic/structures_newrelic_application.go
  website/docs/r/application.html.markdown
Labels: documentation, size/XL

#487 feat(nrql_alert_condition): integrate NerdGraph for nrql alert conditions
  newrelic/config.go
  newrelic/resource_helpers.go
  newrelic/resource_newrelic_nrql_alert_condition.go
  newrelic/resource_newrelic_nrql_alert_condition_test.go
  newrelic/structures_newrelic_nrql_alert_condition.go
Labels: size/XXL

#504 feat(alerts): convert Alerts Policies to nerdgraph
  newrelic/data_source_newrelic_alert_policy.go
  newrelic/helpers.go
  newrelic/helpers_test.go
  newrelic/provider_test.go
  newrelic/resource_helpers.go
  newrelic/resource_newrelic_alert_policy.go
  newrelic/resource_newrelic_alert_policy_test.go
  newrelic/resource_newrelic_nrql_alert_condition_test.go
  newrelic/resource_newrelic_workload_test.go
  newrelic/structures_newrelic_alert_policy.go
  website/docs/r/alert_policy.html.markdown
Labels: documentation, size/XL

#508 chore(alerts): deprecation notice for created_at/updated_at
  newrelic/resource_newrelic_alert_policy.go
  website/docs/r/alert_policy.html.markdown
Labels: documentation, size/XS

#511 docs(alerts): include caveat about NRQL alerts condition operator usa…
  website/docs/r/nrql_alert_condition.html.markdown
Labels: documentation, size/XS

#505 docs(nrql_alert_condition): update docs to reflect version 2.0 changes
  newrelic/resource_newrelic_nrql_alert_condition.go
  newrelic/resource_newrelic_nrql_alert_condition_test.go
  website/docs/d/v1/alert_channel.html.markdown
  website/docs/d/v1/alert_policy.html.markdown
  website/docs/d/v1/application.html.markdown
  website/docs/d/v1/key_transaction.html.markdown
  website/docs/d/v1/plugin.html.markdown
  website/docs/d/v1/plugin_component.html.markdown
  website/docs/d/v1/synthetics_monitor.html.markdown
  website/docs/d/v1/synthetics_secure_credential.html.markdown
  website/docs/r/nrql_alert_condition.html.markdown
  website/docs/r/v1/alert_channel.html.markdown
  website/docs/r/v1/alert_condition.html.markdown
  website/docs/r/v1/alert_policy.html.markdown
  website/docs/r/v1/alert_policy_channel.html.markdown
  website/docs/r/v1/application.html.markdown
  website/docs/r/v1/application_label.html.markdown
  website/docs/r/v1/dashboard.html.markdown
  website/docs/r/v1/infra_alert_condition.html.markdown
  website/docs/r/v1/insights_event.html.markdown
  website/docs/r/v1/nrql_alert_condition.html.markdown
  website/docs/r/v1/plugins_alert_condition.html.markdown
  website/docs/r/v1/synthetics_alert_condition.html.markdown
  website/docs/r/v1/synthetics_label.html.markdown
  website/docs/r/v1/synthetics_monitor.html.markdown
  website/docs/r/v1/synthetics_monitor_script.html.markdown
  website/docs/r/v1/synthetics_secure_credential.html.markdown
  website/docs/r/v1/workload.html.markdown
  website/newrelic.erb
Labels: documentation, size/XXL

#519 fix(newrelic): fix the failing integration tests
  go.mod
  go.sum
  newrelic/resource_newrelic_alert_policy.go
  newrelic/resource_newrelic_application_test.go
  newrelic/resource_newrelic_workload_test.go
  vendor/github.com/hashicorp/go-retryablehttp/README.md
  vendor/github.com/hashicorp/go-retryablehttp/client.go
  vendor/github.com/hashicorp/go-retryablehttp/roundtripper.go
  vendor/github.com/newrelic/newrelic-client-go/internal/http/client.go
  vendor/github.com/newrelic/newrelic-client-go/internal/http/errors.go
  vendor/github.com/newrelic/newrelic-client-go/internal/http/graphql.go
  vendor/github.com/newrelic/newrelic-client-go/internal/testing/config.go
  vendor/github.com/newrelic/newrelic-client-go/internal/version/version.go
  vendor/github.com/newrelic/newrelic-client-go/newrelic/newrelic.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/alerts.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/policies.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/typegen.yaml
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/types.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/config/config.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/infrastructure/infrastructure.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/nerdgraph/nerdgraph.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/nerdgraph/typegen.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/nerdstorage/nerdstorage.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/region/errors.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/region/region.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/region/region_constants.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/synthetics/synthetics.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/workloads/workload.go
  vendor/golang.org/x/tools/go/analysis/analysis.go
  vendor/golang.org/x/tools/go/analysis/internal/checker/checker.go
  vendor/golang.org/x/tools/go/analysis/passes/findcall/findcall.go
  vendor/golang.org/x/tools/go/analysis/passes/unreachable/unreachable.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/internal/analysisinternal/analysis.go
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/golang.org/x/tools/internal/span/parse.go
  vendor/golang.org/x/tools/internal/span/span.go
  vendor/golang.org/x/tools/internal/span/token.go
  vendor/golang.org/x/tools/internal/span/token111.go
  vendor/golang.org/x/tools/internal/span/token112.go
  vendor/golang.org/x/tools/internal/span/uri.go
  vendor/golang.org/x/tools/internal/span/utf16.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#520 docs(alert_channel): fix broken 'nested config' anchor link
  website/docs/r/alert_channel.html.markdown
Labels: documentation, size/XS

#534 chore(deps): Update terraform-plugin-sdk
  go.mod
  go.sum
  vendor/github.com/hashicorp/terraform-plugin-sdk/acctest/doc.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/resource/testing.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/resource/testing_new.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/schema.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/meta/meta.go
  vendor/github.com/hashicorp/terraform-plugin-test/helper.go
  vendor/github.com/hashicorp/terraform-plugin-test/util.go
  vendor/modules.txt
Labels: dependencies, size/XL

#528 feat(dashboard): [v1.x] add grid_column_count to dashboard schema
  newrelic/resource_newrelic_dashboard.go
  newrelic/resource_newrelic_dashboard_test.go
  newrelic/structures_newrelic_dashboard.go
  website/docs/r/dashboard.html.markdown
Labels: documentation, size/M

#535 feat(dashboard): add grid_column_count to dashboard schema
  newrelic/resource_newrelic_dashboard.go
  newrelic/resource_newrelic_dashboard_test.go
  newrelic/structures_newrelic_dashboard.go
  website/docs/r/dashboard.html.markdown
  website/docs/r/v1/dashboard.html.markdown
Labels: documentation, size/M

#510 test(alerts): include additional test condition for "equal" operator
  newrelic/structures_newrelic_alert_condition_test.go
Labels: size/XS
