Repository newrelic/terraform-provider-newrelic, pull requests merged in 2020-05, with the labels that each got.

#543 [v1] chore(docs): Update CHANGELOG
  CHANGELOG.md
Labels: size/XS

#549 Release/v1.17.1
  CHANGELOG.md
  go.mod
  go.sum
  vendor/github.com/newrelic/newrelic-client-go/internal/version/version.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/channels.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/conditions.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/incidents.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/multi_location_synthetics_conditions.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/nrql_conditions.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/plugins_conditions.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/synthetics_conditions.go
  vendor/modules.txt
Labels: dependencies, size/S

#546 docs(getting started): fix resource naming
  website/docs/guides/getting_started.html.markdown
Labels: documentation, size/XS

#550 chore(build): Ask renovate to track release/v1.x branch too
  .github/renovate.json
Labels: size/XS

#556 fix(alerts): infra alert condition zero value detection
  newrelic/resource_newrelic_infra_alert_condition_test.go
  newrelic/structures_newrelic_infra_alert_condition.go
Labels: size/S

#557 fix(alerts): infra alert condition zero value detection
  newrelic/resource_newrelic_infra_alert_condition_test.go
  newrelic/structures_newrelic_infra_alert_condition.go
Labels: size/S

#559 refactor(application): rename resource to application_settings
  newrelic/provider.go
  newrelic/resource_newrelic_application_settings.go
  newrelic/resource_newrelic_application_settings_test.go
  newrelic/structures_newrelic_application_settings.go
  website/docs/r/application_settings.html.markdown
Labels: documentation, size/S

#564 Test updates
  newrelic/resource_newrelic_alert_policy_test.go
  newrelic/resource_newrelic_application_settings.go
  newrelic/resource_newrelic_application_settings_test.go
Labels: size/XS

#576 tests: fix integration tests
  newrelic/resource_newrelic_application_settings_test.go
  website/docs/index.html.markdown
Labels: documentation, size/XS

#579 Release/v1.18.0
  CHANGELOG.md
Labels: size/XXL

#581 Release/v1.18.0
  CHANGELOG.md
Labels: size/XS

#582 docs(application_settings): add application settings resource to sidebar
  website/newrelic.erb
Labels: documentation, size/XS

#586 chore(stale): don't close PRs or issues with 'pinned' label
  .github/stale.yml
Labels: chore, size/XS

#596 Update newrelic-client-go, Add different Issue types to GH
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/objective.md
  go.mod
  go.sum
Labels: dependencies, size/S

#597 chore(docs): Fix bug issue, add issue config
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: bug, documentation, size/XS

#598 refactor(infra_alert_condition): case sensitivity adjustments for type, comparison, and time_function
  newrelic/resource_newrelic_infra_alert_condition.go
  newrelic/resource_newrelic_infra_alert_condition_test.go
  newrelic/structures_newrelic_infra_alert_condition.go
Labels: size/S
