Repository newrelic/terraform-provider-newrelic, pull requests merged in 2020-01, with the labels that each got.

#299 feat: release 1.11.0
  CHANGELOG.md
  go.mod
  go.sum
  vendor/github.com/newrelic/go-insights/client/insert.go
  vendor/github.com/newrelic/go-insights/client/types.go
  vendor/golang.org/x/crypto/internal/chacha20/asm_ppc64le.s
  vendor/golang.org/x/crypto/internal/chacha20/chacha_noasm.go
  vendor/golang.org/x/crypto/internal/chacha20/chacha_ppc64le.go
  vendor/golang.org/x/crypto/openpgp/packet/encrypted_key.go
  vendor/golang.org/x/crypto/openpgp/packet/private_key.go
  vendor/golang.org/x/tools/go/analysis/doc.go
  vendor/golang.org/x/tools/go/analysis/internal/checker/checker.go
  vendor/golang.org/x/tools/go/analysis/passes/asmdecl/asmdecl.go
  vendor/golang.org/x/tools/go/analysis/passes/atomicalign/atomicalign.go
  vendor/golang.org/x/tools/go/analysis/passes/bools/bools.go
  vendor/golang.org/x/tools/go/analysis/passes/buildtag/buildtag.go
  vendor/golang.org/x/tools/go/analysis/passes/cgocall/cgocall.go
  vendor/golang.org/x/tools/go/analysis/passes/errorsas/errorsas.go
  vendor/golang.org/x/tools/go/analysis/passes/findcall/findcall.go
  vendor/golang.org/x/tools/go/analysis/passes/lostcancel/lostcancel.go
  vendor/golang.org/x/tools/go/analysis/passes/printf/printf.go
  vendor/golang.org/x/tools/go/analysis/passes/shadow/shadow.go
  vendor/golang.org/x/tools/go/analysis/passes/shift/shift.go
  vendor/golang.org/x/tools/go/analysis/passes/unmarshal/unmarshal.go
  vendor/golang.org/x/tools/go/packages/doc.go
  vendor/golang.org/x/tools/go/packages/external.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/loadmode_string.go
  vendor/golang.org/x/tools/go/packages/packages.go
  vendor/golang.org/x/tools/go/ssa/builder.go
  vendor/golang.org/x/tools/imports/forward.go
  vendor/golang.org/x/tools/internal/gopathwalk/walk.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/imports.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/golang.org/x/tools/internal/imports/mod_cache.go
  vendor/golang.org/x/tools/internal/span/parse.go
  vendor/golang.org/x/tools/internal/span/span.go
  vendor/golang.org/x/tools/internal/span/token.go
  vendor/golang.org/x/tools/internal/span/token111.go
  vendor/golang.org/x/tools/internal/span/token112.go
  vendor/golang.org/x/tools/internal/span/uri.go
  vendor/golang.org/x/tools/internal/span/utf16.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#304 Update alert_condition.html.markdown
  website/docs/r/alert_condition.html.markdown
Labels: documentation, size/XS

#312 refactor(alerts): update resource_newrelic_infra_alert_condition to u…
  newrelic/resource_newrelic_infra_alert_condition.go
  newrelic/resource_newrelic_infra_alert_condition_test.go
Labels: size/M

#315 chore: prep for 1.12.0 release
  CHANGELOG.md
  go.mod
  go.sum
Labels: size/S

#320 chore(deps): update module newrelic/newrelic-client-go to v0.5.0
  go.mod
  go.sum
  newrelic/provider.go
  vendor/github.com/newrelic/newrelic-client-go/internal/version/version.go
  vendor/github.com/newrelic/newrelic-client-go/newrelic/newrelic.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/entities/entities.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/entities/entities_types.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/entities/tags.go
  vendor/modules.txt
Labels: dependencies, size/XL

#324 Fix API Key passing to newrelic-client-go
  newrelic/provider.go
Labels: bug, size/XS

#325 docs: update alert-channel examples
  website/docs/guides/getting_started.html.markdown
  website/docs/index.html.markdown
  website/docs/r/alert_channel.html.markdown
  website/docs/r/alert_policy_channel.html.markdown
Labels: documentation, size/XS

#338 refactor: migrate alert conditions to newrelic-client-go
  go.mod
  newrelic/resource_newrelic_alert_condition.go
  newrelic/structures.go
  newrelic/structures_newrelic_alert_condition.go
  newrelic/structures_newrelic_alert_condition_test.go
  newrelic/structures_newrelic_nrql_alert_condition.go
  newrelic/structures_newrelic_nrql_alert_condition_test.go
  newrelic/structures_test.go
  vendor/github.com/stretchr/testify/require/doc.go
  vendor/github.com/stretchr/testify/require/forward_requirements.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require.go.tmpl
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#341 refactor: rebase newrelic_alert_policy resource on newrelic-client-go
  go.mod
  go.sum
  newrelic/data_source_newrelic_alert_policy.go
  newrelic/resource_newrelic_alert_policy.go
  newrelic/structures_newrelic_alert_policy.go
  vendor/github.com/newrelic/newrelic-client-go/internal/version/version.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/alerts_types.go
  vendor/modules.txt
Labels: dependencies, size/L

#347 chore(release): prep for v1.12.1 release
  CHANGELOG.md
Labels: size/XS

#348 refactor(alerts): update resource_newrelic_nrql_alert_condition to use new client
  newrelic/resource_newrelic_nrql_alert_condition.go
  newrelic/structures_newrelic_nrql_alert_condition.go
  newrelic/structures_newrelic_nrql_alert_condition_test.go
Labels: size/XL

#351 refactor: rebase applications on newrelic-client-go
  newrelic/data_source_newrelic_application.go
Labels: size/XS

#350 refactor: rebase key txns on newrelic-client-go
  newrelic/data_source_newrelic_key_transaction.go
  newrelic/data_source_newrelic_key_transaction_test.go
Labels: size/XS

#349 refactor: rebase synthetics conditions on newrelic-client-go
  go.mod
  go.sum
  newrelic/resource_newrelic_synthetics_alert_condition.go
  vendor/github.com/newrelic/newrelic-client-go/internal/version/version.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/synthetics_conditions.go
  vendor/modules.txt
Labels: dependencies, size/M

#343 refactor: rebase newrelic_dashboard resource on newrelic-client-go
  newrelic/resource_newrelic_dashboard.go
  newrelic/structures_newrelic_dashboard.go
Labels: size/M

#344 refactor: rebase plugins resources on newrelic-client-go
  newrelic/data_source_newrelic_plugin.go
  newrelic/data_source_newrelic_plugin_component.go
  newrelic/resource_newrelic_plugins_alert_condition.go
  newrelic/structures_newrelic_plugins_alert_condition.go
  newrelic/structures_newrelic_plugins_alert_condition_test.go
Labels: size/XL

#353 refactor: rebase alerts policy channels on newrelic-client-go
  newrelic/data_source_newrelic_synthetics_monitor_test.go
  newrelic/helpers_test.go
  newrelic/resource_newrelic_alert_policy_channel.go
  newrelic/resource_newrelic_alert_policy_channel_test.go
Labels: size/M

#357 refactor(tests): cleanup old applications generated by acceptance test suite
  newrelic/provider_test.go
Labels: size/M

#361 fix(alert_channels): handle more complex JSON structures in payload or headers
  go.mod
  go.sum
  newrelic/structures_newrelic_alert_channel.go
  vendor/github.com/newrelic/newrelic-client-go/internal/http/client.go
  vendor/github.com/newrelic/newrelic-client-go/internal/http/graphql_client.go
  vendor/github.com/newrelic/newrelic-client-go/internal/logging/structured_logger.go
  vendor/github.com/newrelic/newrelic-client-go/internal/version/version.go
  vendor/github.com/newrelic/newrelic-client-go/newrelic/newrelic.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/alerts.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/alerts/alerts_types.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/config/config.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/entities/entities.go
  vendor/github.com/newrelic/newrelic-client-go/pkg/synthetics/synthetics.go
  vendor/modules.txt
Labels: dependencies, size/L

#362 chore: update changelog
  CHANGELOG.md
Labels: size/XS

#358 feat: replace provider backend with newrelic-client-go
  go.mod
  go.sum
  newrelic/config.go
  newrelic/config_test.go
  newrelic/helpers_test.go
  newrelic/provider.go
  newrelic/resource_newrelic_alert_condition.go
  newrelic/resource_newrelic_alert_condition_test.go
  newrelic/resource_newrelic_alert_policy_channel_test.go
  newrelic/resource_newrelic_alert_policy_test.go
  newrelic/resource_newrelic_dashboard_test.go
  newrelic/resource_newrelic_nrql_alert_condition_test.go
  newrelic/resource_newrelic_plugins_alert_condition.go
  newrelic/resource_newrelic_plugins_alert_condition_test.go
  newrelic/resource_newrelic_synthetics_alert_condition_test.go
  vendor/github.com/go-resty/resty/v2/.gitignore
  vendor/github.com/go-resty/resty/v2/.travis.yml
  vendor/github.com/go-resty/resty/v2/BUILD.bazel
  vendor/github.com/go-resty/resty/v2/LICENSE
  vendor/github.com/go-resty/resty/v2/README.md
  vendor/github.com/go-resty/resty/v2/WORKSPACE
  vendor/github.com/go-resty/resty/v2/client.go
  vendor/github.com/go-resty/resty/v2/go.mod
  vendor/github.com/go-resty/resty/v2/middleware.go
  vendor/github.com/go-resty/resty/v2/redirect.go
  vendor/github.com/go-resty/resty/v2/request.go
  vendor/github.com/go-resty/resty/v2/response.go
  vendor/github.com/go-resty/resty/v2/resty.go
  vendor/github.com/go-resty/resty/v2/retry.go
  vendor/github.com/go-resty/resty/v2/trace.go
  vendor/github.com/go-resty/resty/v2/util.go
  vendor/github.com/paultyng/go-newrelic/v4/LICENSE
  vendor/github.com/paultyng/go-newrelic/v4/api/alert_channels.go
  vendor/github.com/paultyng/go-newrelic/v4/api/alert_conditions.go
  vendor/github.com/paultyng/go-newrelic/v4/api/alert_infra_conditions.go
  vendor/github.com/paultyng/go-newrelic/v4/api/alert_nrql_conditions.go
  vendor/github.com/paultyng/go-newrelic/v4/api/alert_plugins_conditions.go
  vendor/github.com/paultyng/go-newrelic/v4/api/alert_policies.go
  vendor/github.com/paultyng/go-newrelic/v4/api/alert_policy_channels.go
  vendor/github.com/paultyng/go-newrelic/v4/api/alert_synthetics_conditions.go
  vendor/github.com/paultyng/go-newrelic/v4/api/applications.go
  vendor/github.com/paultyng/go-newrelic/v4/api/client.go
  vendor/github.com/paultyng/go-newrelic/v4/api/component_metric_data.go
  vendor/github.com/paultyng/go-newrelic/v4/api/component_metrics.go
  vendor/github.com/paultyng/go-newrelic/v4/api/components.go
  vendor/github.com/paultyng/go-newrelic/v4/api/dashboards.go
  vendor/github.com/paultyng/go-newrelic/v4/api/deployments.go
  vendor/github.com/paultyng/go-newrelic/v4/api/key_transactions.go
  vendor/github.com/paultyng/go-newrelic/v4/api/labels.go
  vendor/github.com/paultyng/go-newrelic/v4/api/plugins.go
  vendor/github.com/paultyng/go-newrelic/v4/api/types.go
  vendor/github.com/paultyng/go-newrelic/v4/api/version.go
  vendor/golang.org/x/net/publicsuffix/list.go
  vendor/golang.org/x/net/publicsuffix/table.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#364 docs: Make note about ignoring secrets
  website/docs/guides/getting_started.html.markdown
Labels: documentation, size/S
