Repository newrelic/terraform-provider-newrelic, pull requests merged in 2021-01, with the labels that each got.

#1088 chore(build): Add go-mod-outdated for tools/ to make
  GNUmakefile
  build/deps.mk
  build/lint.mk
  build/tools.mk
  tools/go.mod
  tools/go.sum
Labels: dependencies, enhancement

#1086 Implement GraphQL Dashboard API
  go.mod
  go.sum
  newrelic/provider.go
  newrelic/resource_newrelic_dashboard.go
  newrelic/resource_newrelic_one_dashboard.go
  newrelic/resource_newrelic_one_dashboard_test.go
  newrelic/structures_newrelic_dashboard.go
  newrelic/structures_newrelic_one_dashboard.go
  website/docs/index.html.markdown
  website/docs/r/one_dashboard.html.markdown
Labels: enhancement, priority:high, size:L

#1112 Update for Dashboard API change [CLOSED BETA]
  go.mod
  go.sum
  newrelic/resource_newrelic_one_dashboard.go
  newrelic/resource_newrelic_one_dashboard_test.go
  newrelic/structures_newrelic_one_dashboard.go
  website/docs/r/one_dashboard.html.markdown
Labels: breaking-change, priority:blocker

#1124 Update one_dashboard docs
  tools/go.mod
  tools/go.sum
  website/docs/r/one_dashboard.html.markdown
Labels: dependencies, documentation

#1146 chore: updated nrql_query examples
  website/docs/r/one_dashboard.html.markdown
Labels: documentation

#1159 chore: removed beta section from docs
  website/docs/r/one_dashboard.html.markdown
Labels: documentation

#1160 chore(changelog): Update CHANGELOG for v2.16.0
  CHANGELOG.md
Labels: enhancement, impact:high, new-resource, priority:high, size:M
