Repository newrelic/terraform-provider-newrelic, pull requests merged in 2021-03, with the labels that each got.

#1249 chore(one_dashboard): additional error catching on create + test
  newrelic/resource_newrelic_one_dashboard.go
  newrelic/resource_newrelic_one_dashboard_test.go
Labels: bug

#1250 feat(newrelic_entity): Add ignore_case to name search for entity
  newrelic/data_source_newrelic_entity.go
  newrelic/data_source_newrelic_entity_integration_test.go
  website/docs/d/entity.html.markdown
Labels: enhancement

#1241 feat: Add NRQL Drop Rule support
  newrelic/provider.go
  newrelic/resource_newrelic_nrql_drop_rule.go
  newrelic/resource_newrelic_nrql_drop_rule_test.go
  website/docs/index.html.markdown
  website/docs/r/nrql_drop_rule.html.markdown
  website/newrelic.erb
Labels: enhancement, impact:high, new-resource, size:M

#1259 Alert Policy / Channel fixes
  newrelic/resource_newrelic_alert_channel.go
  newrelic/resource_newrelic_alert_channel_test.go
  newrelic/resource_newrelic_alert_policy_channel.go
  newrelic/resource_newrelic_alert_policy_channel_test.go
  newrelic/resource_newrelic_alert_policy_test.go
  newrelic/structures_newrelic_alert_channel.go
  newrelic/structures_newrelic_alert_channel_test.go
  newrelic/structures_newrelic_alert_policy_channel.go
  tools/go.mod
  tools/go.sum
  website/docs/r/alert_channel.html.markdown
Labels: bug
